//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int activityID { get; set; }
        public string activityName { get; set; }
        public string activityDuration { get; set; }
        public System.DateTime activityDate { get; set; }
        public int cost { get; set; }
        public bool IsSaved { get; set; }
        public bool IsBooked { get; set; }
    }
}
