//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Air
    {
        public int airId { get; set; }
        public int ticketNumber { get; set; }
        public string departureStation { get; set; }
        public string destinationStation { get; set; }
        public System.TimeSpan arrivalTime { get; set; }
        public System.TimeSpan departureTime { get; set; }
        public string duration { get; set; }
        public int price { get; set; }
        public bool IsSaved { get; set; }
        public bool IsBooked { get; set; }
    }
}
