//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int carId { get; set; }
        public string carName { get; set; }
        public string carCompany { get; set; }
        public string carModel { get; set; }
        public int cost { get; set; }
        public string color { get; set; }
        public string engine { get; set; }
        public bool IsSaved { get; set; }
        public bool IsBooked { get; set; }
    }
}
