//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public bool IsBooked { get; set; }
        public bool IsSaved { get; set; }
        public string address { get; set; }
        public int fare { get; set; }
        public int hotelId { get; set; }
        public string hotelName { get; set; }
        public int rating { get; set; }
        public int roomsAvailable { get; set; }
        public bool wifiAvailability { get; set; }
    }
}
